# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34331cb6962cd8d2a3aee6a8e7f1c9bee29a8cb0c23c19a65e84995561fc3eae3384dfa298e335db02b76f4de3c99a39fdeeb755df05780a761c0ad70dbf9932

test:
  secret_key_base: e2d6a91640d49f9399de5125386abb3d579d387a28314942432e22883db714fb9739a23e753580af22d6a6656c7d1014999b0f3bf4d58a5a228978692b9d06bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
